### ISSUE TITLE
Is using a time.time is correct?

### ISSUE THREAD

**Issue by worldmind** [brunowerneck/benchmark-decorator#1]
It is not simple topic, but as I understood using time difference not always correct even in simple script because OS can pause a process and it is make more complex if we in thread environment.
Maybe [SO](https://stackoverflow.com/questions/7370801/measure-time-elapsed-in-python) can explain better.

**Comment by worldmind** [comment]
As I can see [profilehooks](https://github.com/mgedmin/profilehooks) use timeit

**Comment by brunowerneck** [comment]
Why wouldn't it be?
An issue is not an issue unless you provide code demonstrating its problem. 
Please fork it, create a new branch, test your case and reopen it if you find any problems.
Thank you.
